[images]
  remote_images = [
    "https://ext.same-assets.com/**",
    "https://cdn1.codashop.com/**",
    "https://placehold.co/**"
  ]

[build]
  command = "bun run build"
  publish = "out"

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs"
